name: Update AI News

on:
  schedule:
    - cron: "0 */3 * * *" # каждые 3 часа
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run news generator
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: python generate_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Update news"
          git push
