name: Автогенерация новостей ИИ

on:
  schedule:
    - cron: "0 */3 * * *"  # каждые 3 часа
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          pip install requests googletrans==4.0.0-rc1 pillow feedparser

      - name: Запуск скрипта генерации
        run: python scripts/generate_news.py

      - name: Коммит и пуш изменений
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add news.json images/
          git commit -m "Автообновление новостей"
          git push
